version: '3'
services:
  # Benchmark runner
  benchmark-runner:
    image: pyasyncio-benchmark:latest
    deploy:
      replicas: 2
    environment:
      DB_FILEPATH: "/var/data/sqlite.db"
    command:
      - python
      - main.py
      - ${LIBRARY_NAME}
      - ${TEST_NAME}
    volumes:
      - ${PWD}/sqlite.db:/var/data/sqlite.db