version: '3'
services:
  # Benchmark runner
  benchmark-runner:
    image: pyasyncio-benchmark:${IMAGE_TAG}
    deploy:
      replicas: 1
    environment:
      DB_FILEPATH: "/var/data/sqlite.db"
      RUN_ID: ${RUN_ID}
    volumes:
      - ${PWD}/sqlite.db:/var/data/sqlite.db
      - /var/run/docker.sock:/var/run/docker.sock