version: '3'
services:
  # Benchmark runner
  benchmark-runner:
    image: pyasyncio-benchmark:${IMAGE_TAG}
    deploy:
      replicas: ${REPLICA_COUNT?error}
    environment:
      DB_FILEPATH: "/var/data/sqlite.db"
    volumes:
      - ${PWD}/sqlite.db:/var/data/sqlite.db
      - /var/run/docker.sock:/var/run/docker.sock