version: '3'
services:
  # Benchmark runner
  benchmark-runner:
    image: pyasyncio-benchmark:latest
    deploy:
      replicas: 10
    entrypoint:
      - python
      - -m
      - benchmark.tests.${TEST_NAME}