version: '3'
services:
  # Benchmark runner
  benchmark-runner:
    image: pyasyncio-benchmark:latest
    deploy:
      replicas: 10
    command:
      - python
      - main.py
      - ${LIBRARY_NAME}
      - ${TEST_NAME}